name: CICD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t syam405/movie-service .
      - name: Publish Image to Docker Hub
        run: docker push syam405/movie-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and Install Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{secrets.EC2_KEY}} ec2-user@${{secrets.EC2_PUBLIC_IP}} << 'EOF'
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -aG docker ec2-user
          sudo chkconfig docker on
          EOF

      - name: Pull Image from Docker Hub
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{secrets.EC2_KEY}} ec2-user@${{secrets.EC2_PUBLIC_IP}} << 'EOF'
          sudo docker pull syam405/movie-service:latest
          EOF

      - name: Remove Old Running Container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{secrets.EC2_KEY}} ec2-user@${{secrets.EC2_PUBLIC_IP}} << 'EOF'
          sudo docker rm -f movie-service-container || true
          EOF

      - name: Run Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{secrets.EC2_KEY}} ec2-user@${{secrets.EC2_PUBLIC_IP}} << 'EOF'
          sudo docker run -d -p 8080:8080 --name movie-service-container syam405/movie-service:latest
          EOF
